### Universidad Galileo 
### Postgrado en Análisis y predicción de Datos
### Ciencia de Datos en Python
### Nixon Armando López Claudio 
### Hoja de Trabajo #3 - Análisis de Datos con Python

<h1><center> Análisis de Datos con Python </center></h1>

In [1]:
import numpy as np
import pandas as pd
import sys
import matplotlib.pyplot as plt

<h1><center> Parte 1: Numpy </center></h1>

#### Para los ejercicios siguiente genere el código que considere para resolver el problema que se le plantea.

1) ¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?

In [2]:
arreglo = np.full(1000, False, dtype=bool)

size = arreglo.nbytes

print(f'El tamaño en bytes de un array de 1000 elementos es de : {size}')

El tamaño en bytes de un array de 1000 elementos es de : 1000


2) Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente. Muestre los 10 últimos por pantalla.

In [3]:
enteros = np.arange(100, 0, -2)
print(f'Los últimos 10 elementos enteros pares del arreglo son {enteros[-10:]}')

Los últimos 10 elementos enteros pares del arreglo son [20 18 16 14 12 10  8  6  4  2]


3) Dado el array

2 4 5 6

0 3 7 4

8 8 5 2

1 5 6 1

In [4]:
array = np.array([[2, 4, 5, 6],[0, 3, 7, 4],[8, 8, 5, 2],[1, 5, 6, 1]])
array

array([[2, 4, 5, 6],
       [0, 3, 7, 4],
       [8, 8, 5, 2],
       [1, 5, 6, 1]])

Seleccione con una instrucción el subarray de elementos
0 3 7 4

In [5]:
subarray = array[1, :]
print(f'El sub arreglo dado el array es: {subarray}')

El sub arreglo dado el array es: [0 3 7 4]


Después, seleccione el subarray de elementos 

2 5

8 5

In [6]:
subarray1 = ([array[0][0], array[0][2]]  , [array[2][0], array[2][2]])

print(f'El sub arreglo dado el array 2,5 y 8,5 es: {subarray1}')

El sub arreglo dado el array 2,5 y 8,5 es: ([2, 5], [8, 5])


4) Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9], obtenga la media aritmética de la diferencia (a-b).

In [7]:
a = np.array([1, 4, 2, 7])
b = np.array([1, 3, 2, 9])

media = np.sum(a-b)/len(a)

In [8]:
print(f'La media arimética de la diferencia (a-b) es: {media}')

La media arimética de la diferencia (a-b) es: -0.25


5) Tengo valores de cordenadas (x, y) en las columnas
del array
1.33 4.5
30.0 10.7
70.2 0.5

Agregue a este array las coordenadas (37.1, -3.6).
Muestre en pantalla las dimensiones del nuevo
array.




In [9]:
coordenadas = np.array([[1.33,4.5],[30.0,10.7],[70.2,0.5]])
coordenadas

array([[ 1.33,  4.5 ],
       [30.  , 10.7 ],
       [70.2 ,  0.5 ]])

In [10]:
nuevas_coordenadas = np.array([37.1,-3.6])
nuevas_coordenadas


array([37.1, -3.6])

In [11]:
coordenadas = np.append(coordenadas, [nuevas_coordenadas], axis = 0)

print("Las coordenadas actualizadas son: {coo}".format(coo=coordenadas))

Las coordenadas actualizadas son: [[ 1.33  4.5 ]
 [30.   10.7 ]
 [70.2   0.5 ]
 [37.1  -3.6 ]]


6. Copie el array del ejercicio anterior. Traspóngalo (.
Agregue ahora dos nuevos pares de coordenadas: (10.8,
3.0) y (35.8, 12.0).

In [12]:
trans = np.transpose(coordenadas)
trans

array([[ 1.33, 30.  , 70.2 , 37.1 ],
       [ 4.5 , 10.7 ,  0.5 , -3.6 ]])

In [13]:
narr = np.array([[10.8,3.0],[35.8,12.0]])
narr

array([[10.8,  3. ],
       [35.8, 12. ]])

In [14]:
actualiza_coordenadas = np.append(trans,np.atleast_2d(narr).T, axis=1 )
print(actualiza_coordenadas)

[[ 1.33 30.   70.2  37.1  10.8  35.8 ]
 [ 4.5  10.7   0.5  -3.6   3.   12.  ]]


<h1><center> Parte 1: Exploración y Minería de Datos </center></h1>

Con el dataset nucleospoblacion.csv adjunto al laboratorio,
luego responda las siguientes preguntas usando pandas y
matplotlib.

In [15]:
import os

In [17]:
os.getcwd()

'd:\\Archivos Nixon\\BAKUP NIXON\\Maestría en Data Science\\1 Trimestre primero DS\\Ciencia de Datos en Python\\Tareas_CDP\\Tarea3.cdp\\tarea3_Analisis_Datos_Python'

1) ¿Cuántos Municipios tienen más de 100000 habitantes?.

2) Realice una gráfica de barras sobre la polbación de cada ciudad, ordenela de menor a mayo y responda:
* ¿Cuál es la segunda ciudad más poblada?
* ¿Qué posición ocupa Granada en el ranking de las ciudades más pobladas?

3) ¿Cuántos municipios de Extremadura tienen más de 5000 habitantes?.

4) ¿Cuál es el municipio situado más al Norte? (Usar el valor de la coordenada "Y" que representa la latitud en grados). Proporcione también la provincia a la que pertenece y su población.

5) Obtenga la media, mediana, desviación estándar, valor máximo y valor mínimo de la población de los municipios de la provincia de Granada.

6) Realice un histograma con la población de los Municipios para cada una de las provincias.

7) Seleccione al azar cincuenta municipios diferentes de entre los diponibles en el archivo. Asegúrese de que no se repitan. ¿Luego calcule el promedio de la población y la desviación estándar de esto 50 municipios?.

8) Dígame los nombres de los Municipios más cercano y más lejano a Madrid. Para ello debe calcular la distancia en todos ellos y Madrid. No considere a Madrid en el análisis ya que la distancia sería cero.